### ISSUE TITLE
Sync only favorite tracks and no playlist

### ISSUE THREAD

**Issue by Sildenafil99** [timrae/spotify_to_tidal#73]
Hello and thanks for your work.
I tried using the tool but I can only synchronize favorite songs and not playlists.
Maybe I'm doing something wrong?

This is the output

PS C:\Temporary\spotify_to_tidal-main> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Login with the webbrowser: link.tidal.com/*****
Loading Spotify playlists
Loading playlists from Tidal user
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 6/6 [00:00<00:00, 27.29it/s]
Loading existing favorite tracks from Tidal
Searching Tidal for 122/122 tracks in Spotify playlist 'Favorites': 100%|████████████| 122/122 [00:15<00:00,  7.68it/s]
Could not find track 5ZKkEVSHfx6enyRJ7DFrFd: Junkie XL - Infinity
Could not find track 7g8pKtAeH3sKk75aKrIpDN: DJ Phellix,Johny Luv - Gentle Night
Could not find track 08FUzof6NqG8kQEsNmkWDh: Bronski Beat,Bourlingueurs - Smalltown Boy (Remix)
Could not find track 0bFaLfdRlQdgkg9MT7L8CQ: Edward Botero - No Man No Cry
Adding new tracks to Tidal favorites: 100%|██████████████████████████████████████████| 118/118 [00:17<00:00,  6.86it/s]
PS C:\Temporary\spotify_to_tidal-main>

**Comment by timrae** [comment]
What does your config file look like?

**Comment by Sildenafil99** [comment]
```
spotify:
  client_id: ef628a5c0fdb******************************
  client_secret: 353d393f85**************************
  username: 116*******
  redirect_uri: http://localhost:8888/callback


# uncomment this block if you want to only sync specific playlist IDs
#sync_playlists:
#  - spotify_id: 1ABCDEqsABCD6EaABCDa0a
#    tidal_id: a0b1234-0a1b-012a-abcd-a1b234c5d6d7

# uncomment this block if you want to sync all playlists in the account with some exceptions
#excluded_playlists:
#  - spotify:playlist:1ABCDEqsABCD6EaABCDa0a

# default setting for syncing favorites when no command line arguments are provided
#   - when true:  favorites will be synced by default (overriden when any command line arg provided)
#   - when false: favorites can only be synced manually via --sync-favorites argument
sync_favorites_default: true

# increasing these parameters should increase the search speed, while decreasing reduces likelihood of 429 errors
max_concurrency: 10 # max concurrent connections at any given time
rate_limit:      10 # max sustained connections per second
```
